name: user_repository
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  fav_qs_api:
    path: ../fav_qs_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  rxdart: ^0.27.1
  flutter_secure_storage: ^4.2.0

dev_dependencies:
  mockito: ^5.2.0
  test: ^1.16.8
  lints: ^1.0.1
  build_runner: ^2.0.5