name: quote_details
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  share_plus: ^4.0.10
  flutter:
    sdk: flutter
  quote_repository:
    path: ../../quote_repository
  domain_models:
    path: ../../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.1.4
  test: ^1.16.8
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true