name: key_value_storage
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  hive: 2.0.4
  path_provider: ^2.0.2

dev_dependencies:
  build_runner: ^2.0.5
  hive_generator: ^1.1.0
  lints: ^1.0.1
  test: ^1.16.8